In [1]:
%reload_kedro

[02/05/24 20:01:52] INFO     Resolved project path as:                                              ]8;id=210187;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=557245;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py#146\146]8;;\
                             /home/jamontanac/Documents/AdversarialExamples/adversarialexamples.                   
                             To set a different path, run '%reload_kedro <project_root>'                           

                    INFO     Kedro project AdversarialExamples                                      ]8;id=206893;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=435294;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py#115\115]8;;\

                    INFO     Defined global variable 'context', 'session', 'catalog' and            ]8;id=568761;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=190727;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py#116\116]8;;\
                             'pipelines'                                                                           

[02/05/24 20:01:53] INFO     Registered line magic 'run_viz'                                        ]8;id=92001;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py\__init__.py]8;;\:]8;id=970226;file:///home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/ipython/__init__.py#122\122]8;;\

In [2]:
from torchvision import transforms, datasets
from torch.utils.data import DataLoader
import torch

In [9]:
transform = transforms.Compose([
    transforms.ToTensor(),  # Converts image to Tensor and scales to [0, 1]
    # Add other transformations if needed
])

dataset = datasets.CIFAR10(root="../data/01_raw/", train=True, transform=transform)
loader = DataLoader(dataset, batch_size=128, shuffle=True)


In [10]:
loader = DataLoader(dataset, batch_size=128, shuffle=True)
for images, _ in loader:
    batch_size, channels, height, width = images.shape
    print(f"Image resolution: {height}x{width}")

Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution: 32x32
Image resolution

In [44]:
def compute_mean_std(loader):
    channels_sum, channels_squared_sum, num_batches = 0, 0, 0

    for data, _ in loader:
        # print(data.size())
        channels_sum += torch.mean(data, dim=[0, 2, 3])
        channels_squared_sum += torch.mean(data ** 2, dim=[0, 2, 3])
        num_batches += 1

    mean = channels_sum / num_batches
    std = (channels_squared_sum / num_batches - mean ** 2) ** 0.5
    print(mean, std)
    return mean, std


In [45]:
mean, std = compute_mean_std(loader)

tensor([0.4914, 0.4822, 0.4466]) tensor([0.2470, 0.2435, 0.2616])


In [1]:
from torchvision import transforms, datasets
from torch.utils.data import DataLoader
import torch

In [8]:
import os
import shutil

# Define the paths to your 'train', 'test', and 'valid' folders

base_path = "/home/jamontanac/Documents/AdversarialExamples/adversarialexamples/data/01_raw/art_dataset"
train_path = os.path.join(base_path, 'train')
valid_path = os.path.join(base_path, 'valid')

# List all subdirectories in both 'train' and 'valid'
train_subdirs = [d for d in os.listdir(train_path) if os.path.isdir(os.path.join(train_path, d))]
valid_subdirs = [d for d in os.listdir(valid_path) if os.path.isdir(os.path.join(valid_path, d))]

# Identify matching subdirectories
matching_subdirs = set(train_subdirs).intersection(valid_subdirs)



In [11]:
for subdir in matching_subdirs:
    valid_subdir_path = os.path.join(valid_path, subdir)
    train_subdir_path = os.path.join(train_path, subdir)
    
    for file in os.listdir(valid_subdir_path):
        src_file_path = os.path.join(valid_subdir_path, file)
        dst_file_path = os.path.join(train_subdir_path, file)
        
        # Move the file
        shutil.move(src_file_path, dst_file_path)
        print(f"Moved {file} from {valid_subdir_path} to {train_subdir_path}")

print("All matching files have been moved.")

Moved alma-woodsey-thomas_evening-glow-1972_jpg.rf.3fc16824aae0e8429c78c4796bc78009.jpg from /home/jamontanac/Documents/AdversarialExamples/adversarialexamples/data/01_raw/art_dataset/valid/Color_Field_Painting to /home/jamontanac/Documents/AdversarialExamples/adversarialexamples/data/01_raw/art_dataset/train/Color_Field_Painting
Moved anne-truitt_untitled-no-11-1983_jpg.rf.b9dddb67f01bed88be4ecde230ece742.jpg from /home/jamontanac/Documents/AdversarialExamples/adversarialexamples/data/01_raw/art_dataset/valid/Color_Field_Painting to /home/jamontanac/Documents/AdversarialExamples/adversarialexamples/data/01_raw/art_dataset/train/Color_Field_Painting
Moved barnett-newman_canto-v-1963_jpg.rf.c5027d60944622d6cd00dd6ce4ccaed5.jpg from /home/jamontanac/Documents/AdversarialExamples/adversarialexamples/data/01_raw/art_dataset/valid/Color_Field_Painting to /home/jamontanac/Documents/AdversarialExamples/adversarialexamples/data/01_raw/art_dataset/train/Color_Field_Painting
Moved claude-viallat

In [6]:
from torchvision import transforms, datasets
from torch.utils.data import DataLoader
import torch

# Define the path to the dataset
dataset_path = "../data/01_raw/art_dataset/train"
# dataset_path = "../data/01_raw/art_dataset/test"

# Define the transformations to apply to the images
transform = transforms.Compose([
    transforms.ToTensor(),  # Convert the images to tensors
])

# Create the dataset
dataset = datasets.ImageFolder(dataset_path, transform=transform)

# Get the classes from the dataset
classes = dataset.classes

# Print the classes
print(classes,len(classes))


['Abstract_Expressionism', 'Action_painting', 'Analytical_Cubism', 'Art_Nouveau_Modern', 'Baroque', 'Color_Field_Painting', 'Contemporary_Realism', 'Cubism', 'Early_Renaissance', 'Expressionism', 'Fauvism', 'High_Renaissance', 'Impressionism', 'Mannerism_Late_Renaissance', 'Minimalism', 'Naive_Art_Primitivism', 'New_Realism', 'Northern_Renaissance', 'Pointillism', 'Pop_Art', 'Post_Impressionism', 'Realism', 'Rococo', 'Romanticism', 'Symbolism', 'Synthetic_Cubism', 'Ukiyo_e'] 27


In [8]:
 # make a code that allows me to see the resolution of the images in the dataloader

loader = DataLoader(dataset, batch_size=128, shuffle=True)
for images, _ in loader:
    batch_size, channels, height, width = images.shape
    print(f"Image resolution: {height}x{width}")



Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolution: 416x416
Image resolu

In [7]:

loader = DataLoader(dataset, batch_size=128, shuffle=True)
def compute_mean_std(loader):
    channels_sum, channels_squared_sum, num_batches = 0, 0, 0

    for data, _ in loader:
        # print(data.size())
        channels_sum += torch.mean(data, dim=[0, 2, 3])
        channels_squared_sum += torch.mean(data ** 2, dim=[0, 2, 3])
        num_batches += 1

    mean = channels_sum / num_batches
    std = (channels_squared_sum / num_batches - mean ** 2) ** 0.5
    print(mean, std)
    return mean, std


mean, std = compute_mean_std(loader)

tensor([0.5195, 0.4650, 0.4011]) tensor([0.2804, 0.2725, 0.2692])


In [ ]:
tensor([0.5194, 0.4651, 0.4013]) tensor([0.2754, 0.2675, 0.2646])

In [2]:

from kedro.config import ConfigLoader
from kedro.framework.project import settings
conf_loader = ConfigLoader(conf_source=settings.CONF_SOURCE)
parameters = conf_loader["parameters"]

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in <module>:1                                                                                    │
│                                                                                                  │
│ ❱ 1 from kedro.config import ConfigLoader                                                        │
│   2 from kedro.framework.project import settings                                                 │
│   3 conf_loader = ConfigLoader(conf_source=settings.CONF_SOURCE)                                 │
│   4 parameters = conf_loader["parameters"]                                                       │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: cannot import name 'ConfigLoader' from 'kedro.config' 
(/home/jamontanac/miniconda3/envs/AdvExamples/lib/python3.10/site-packages/kedro/config/__init__.py)

In [2]:
settings.CONF_SOURCE

'conf'

In [9]:

from kedro.config import OmegaConfigLoader
# from kedro.config import ConfigLoader
from kedro.framework.project import settings

CONFIG_LOADER_CLASS = OmegaConfigLoader(conf_source='../'+settings.CONF_SOURCE+'/art')
# conf_loader = ConfigLoader(conf_source=settings.CONF_SOURCE)
# parameters = conf_loader["parameters"]
parameters = CONFIG_LOADER_CLASS['parameters']
print(CONFIG_LOADER_CLASS)

OmegaConfigLoader(conf_source=../conf/art, env=None, config_patterns={'catalog': ['catalog*', 'catalog*/**', '**/catalog*'], 'parameters': ['parameters*', 'parameters*/**', '**/parameters*'], 'credentials': ['credentials*', 'credentials*/**', '**/credentials*'], 'globals': ['globals.yml']})


In [12]:
CONFIG_LOADER_CLASS['catalog']['Dataset_for_test']['mean']

[0.5195, 0.465, 0.4011]